# Generated by Django 4.2.16 on 2026-09-21 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_position', models.PositiveIntegerField(help_text='Relative priority ranking (1 = highest priority)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(help_text='Target clinical case', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='cases.case')),
                ('hypothesis', models.ForeignKey(help_text='Ranked diagnostic hypothesis', on_delete=django.db.models.deletion.CASCADE, related_name='ranking_entries', to='collaboration.hypothesis')),
            ],
            options={
                'db_table': 'cases_diagnosisranking',
                'ordering': ['rank_position'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_diagnosis', models.CharField(help_text='Definitive clinical diagnosis', max_length=250)),
                ('advisory_acknowledged', models.BooleanField(default=False, help_text='Mandatory legal acknowledgment that specialist advice is advisory')),
                ('governance_statement', models.TextField(help_text='Rendered text of governance modal statement agreed to')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(help_text='Target clinical case (Enforces 1 decision per case)', on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='cases.case')),
                ('decider', models.ForeignKey(help_text='Attending Primary Physician who recorded the decision', on_delete=django.db.models.deletion.PROTECT, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases_decision',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='diagnosisranking',
            constraint=models.UniqueConstraint(fields=('case', 'hypothesis'), name='unique_case_hypothesis_rank'),
        ),
        migrations.AddConstraint(
            model_name='diagnosisranking',
            constraint=models.UniqueConstraint(fields=('case', 'rank_position'), name='unique_case_rank_position'),
        ),
        migrations.AddConstraint(
            model_name='diagnosisranking',
            constraint=models.CheckConstraint(check=models.Q(('rank_position__gt', 0)), name='rank_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(check=models.Q(('advisory_acknowledged', True)), name='decision_must_acknowledge_advisory'),
        ),
    ]
