# Generated by Django 4.2.16 on 2026-09-21 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_diagnosisranking_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CLINICAL_PHOTO', 'Clinical Photo (Dermatology, Wound, Eye)'), ('RADIOLOGY', 'Imaging (X-Ray, CT, MRI, Ultrasound)'), ('WAVEFORM', 'Electrophysiology (ECG, EEG Tracing)'), ('LAB_PDF', 'Laboratory / Pathology PDF Report'), ('OTHER', 'Other Diagnostic Media')], default='OTHER', max_length=30)),
                ('title', models.CharField(help_text='Clinical description of the diagnostic media or study', max_length=200)),
                ('file', models.FileField(help_text='Sanitized diagnostic file (JPEG, PNG, WebP, PDF)', upload_to='case_attachments/%Y/%m/')),
                ('mime_type', models.CharField(help_text='Verified MIME content-type', max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases_attachment',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
