# Generated by Django 4.2.16 on 2026-09-22 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='bp_diastolic',
            field=models.PositiveIntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='bp_systolic',
            field=models.PositiveIntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='heart_rate_bpm',
            field=models.PositiveIntegerField(blank=True, help_text='Heart rate in beats per minute (bpm)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, help_text='Blood oxygen saturation percentage SpO2 (%)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Respiratory rate in breaths per minute (/min)', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius (°C)', max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='CaseLabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text='Diagnostic test or panel name (e.g. Serum Ferritin, WBC, Hemoglobin)', max_length=120)),
                ('value', models.CharField(help_text='Quantitative result or finding (e.g. 4200, 18.5, Positive)', max_length=60)),
                ('unit', models.CharField(blank=True, help_text='Measurement unit (e.g. ng/mL, x10^9/L, g/dL)', max_length=40)),
                ('reference_range', models.CharField(blank=True, help_text='Standard physiological reference interval (e.g. 15-200 ng/mL)', max_length=80)),
                ('flag', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('LOW', 'Low'), ('CRITICAL', 'Critical'), ('ABNORMAL', 'Abnormal')], default='NORMAL', help_text='Clinical abnormality classification', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='cases.case')),
            ],
            options={
                'db_table': 'cases_labresult',
                'ordering': ['created_at'],
            },
        ),
    ]
