# Generated by Django 4.2.16 on 2026-09-21 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('CASE_CREATED', 'Case Created'), ('SPECIALIST_ADMITTED', 'Specialist Admitted'), ('HYPOTHESIS_SUBMITTED', 'Hypothesis Submitted'), ('HYPOTHESIS_WITHDRAWN', 'Hypothesis Withdrawn'), ('DISCUSSION_POSTED', 'Discussion Posted'), ('RANK_UPDATED', 'Rank Updated'), ('DECISION_RECORDED', 'Decision Recorded'), ('ACCESS_DENIED', 'Access Denied')], max_length=50)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('case_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ALLOWED', 'Allowed'), ('DENIED', 'Denied')], default='ALLOWED', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
