# Generated by Django 4.2.16 on 2026-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('CASE_CREATED', 'Case Created'), ('SPECIALIST_ADMITTED', 'Specialist Admitted'), ('HYPOTHESIS_SUBMITTED', 'Hypothesis Submitted'), ('HYPOTHESIS_WITHDRAWN', 'Hypothesis Withdrawn'), ('DISCUSSION_POSTED', 'Discussion Posted'), ('RANK_UPDATED', 'Rank Updated'), ('DECISION_RECORDED', 'Decision Recorded'), ('ATTACHMENT_UPLOADED', 'Attachment Uploaded'), ('ATTACHMENT_ACCESSED', 'Attachment Accessed'), ('FINDINGS_UPDATED', 'Findings Updated'), ('REPORT_GENERATED', 'Report Generated'), ('ACCESS_DENIED', 'Access Denied')], max_length=50),
        ),
    ]
