# Generated by Django 4.2.16 on 2026-09-21 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_diagnosis', models.CharField(help_text='Diagnostic label proposed by specialist', max_length=250)),
                ('rationale', models.TextField(help_text='Pathophysiological reasoning (min 20 chars)')),
                ('supporting_evidence', models.TextField(help_text='Specific references to clinical findings and labs (min 20 chars)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='ACTIVE', max_length=20)),
                ('withdrawal_reason', models.TextField(blank=True, help_text='Explanatory clinical rationale when marked withdrawn', null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='UTC timestamp when hypothesis was withdrawn', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when hypothesis was recorded')),
                ('case', models.ForeignKey(help_text='Target clinical case', on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='cases.case')),
                ('specialist', models.ForeignKey(help_text='Submitting specialist', on_delete=django.db.models.deletion.PROTECT, related_name='hypotheses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collaboration_hypothesis',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='collaborati_case_id_de6fa8_idx'), models.Index(fields=['specialist'], name='collaborati_special_dab6c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscussionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(help_text='Narrative clinical deliberation or query', max_length=2000)),
                ('posted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC posting timestamp')),
                ('author', models.ForeignKey(help_text='Physician or specialist posting the note', on_delete=django.db.models.deletion.PROTECT, related_name='discussion_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(help_text='Target clinical case', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_notes', to='cases.case')),
            ],
            options={
                'db_table': 'collaboration_discussionnote',
                'ordering': ['posted_at'],
                'indexes': [models.Index(fields=['case', 'posted_at'], name='collaborati_case_id_675f75_idx')],
            },
        ),
    ]
